name = "MyRegistry"
uuid = "c0cdd978-a081-4530-acb7-b61dfcd10aa2"
repo = "https://github.com/michaelbennett99/MyRegistry.jl"
description = "My registry"

[packages]
fd3c36b2-d619-4b64-906f-73477278ed8e = { name = "NumericalMethods", path = "N/NumericalMethods" }
